### ISSUE TITLE
 issue that this cannot read certain srt files 

### ISSUE THREAD

**Issue by Yang321423** [shiyiya/flutter_subtitle#3]
I am using this package for my app.
this is really good.
But I am having an unknown error recently. 
This package has an error that it cannot read certain srt files and I cannot figure out why.

Can you figure out the reason and update flutter subtitle?
I am attaching one of the srt files that is causing the error.
[srtwithissue.zip](https://github.com/user-attachments/files/16846626/srtwithissue.zip)

**Comment by shiyiya** [comment]
Please provide error information and reproduce the environment.

**Comment by shiyiya** [comment]
There are extra blank lines at end line.

**Comment by shiyiya** [comment]
fixed 0.0.5
